### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Bartcardi** [olirice/flupy#5]
When toying around with your library and testing some snippets of your API reference I noticed that the first example of `group_by` results in an error when comparing `str` with `int`:

```python
>>> from flupy import flu
>>> flu.group_by([1, 'a', 'a', 1, 1]).collect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bjoosten/.pyenv/versions/3.6.3/lib/python3.6/site-packages/flupy/fluent.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Users/bjoosten/.pyenv/versions/3.6.3/lib/python3.6/site-packages/flupy/fluent.py", line 235, in group_by
    gen = self.sort(key) if sort else self
  File "/Users/bjoosten/.pyenv/versions/3.6.3/lib/python3.6/site-packages/flupy/fluent.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Users/bjoosten/.pyenv/versions/3.6.3/lib/python3.6/site-packages/flupy/fluent.py", line 204, in sort
    return Fluent(sorted(self, key=key, reverse=reverse))
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by olirice** [comment]
Thanks for reporting, the docs have been fixed.

While updating the docs, I also came across an issue with `group_by` when a key function was provided. That was similarly fixed in version 1.0.10, which is now on pypi. So if you plan to continue working through the docs please `pip install -U flupy` first

938ce4ac8b12b87b9934b43102387c32433932e7
